QT.Qt5Keychain.VERSION = 0.13.2
QT.Qt5Keychain.MAJOR_VERSION = 0
QT.Qt5Keychain.MINOR_VERSION = 13
QT.Qt5Keychain.PATCH_VERSION = 2
QT.Qt5Keychain.name = qt5keychain
QT.Qt5Keychain.module = qt5keychain
QT.Qt5Keychain.defines = 
QT.Qt5Keychain.includes = /usr/include
QT.Qt5Keychain.private_includes =
QT.Qt5Keychain.libs = /usr/lib
QT.Qt5Keychain.depends = core dbus
QT.Qt5Keychain.module_config = 
